debug: true

messages:
  prefix: "&a&o&l[Block&b&o&lEntities] &7&o"

  reloaded: Plugin settings have been reloaded
  cantReload: You don't have permissions to reload the settings
  cantGet: You don't have permissions to get this block
  cantPlace: You don't have permissions to place this block
  cantBreak: You don't have permissions to break this block
  commandBlockMissing: Please provide the name of the block you want to get
  commandBlockNotExists: The given block name does not exist, please provide a valid one
  commandNotPlayer: Only a player can execute this command

blocks:
  - key: braid
    displayName: "&b&oBraid"
    lore: []
    customModelData: 1000
  - key: dots
    displayName: "&b&oDots"
    lore: []
    customModelData: 1001
  - key: goldplate
    displayName: "&b&oGoldplate"
    lore: []
    customModelData: 1002
  - key: hazard
    displayName: "&b&oHazard"
    lore: []
    customModelData: 1003
  - key: hazardorange
    displayName: "&b&oHazard Orange"
    lore: []
    customModelData: 1004
  - key: mosaice
    displayName: "&b&oMosaic"
    lore: []
    customModelData: 1005
  - key: platex
    displayName: "&b&oPlatex"
    lore: []
    customModelData: 1006
  - key: rust
    displayName: "&b&oRust"
    lore: []
    customModelData: 1007
  - key: wireframe
    displayName: "&b&oWireframe"
    lore: []
    customModelData: 1008