name: BlockEntities
version: 1.0.0
authors:
  - Artcas2
  - dannegm
main: fr.artcas2.BlockEntitiesPlus.BlockEntitiesPlus
api-version: 1.19

commands:
  blockentitiesplus:
    description: BlockEntities base command
    usage: /blockentitiesplus help

permissions:
  blockentitiesplus.reload:
    description: Allows to execute the reload command
    default: false
  blockentitiesplus.get:
    description: Allows to use the get command to the players
    default: false
  blockentitiesplus.place:
    description: Allows to place blocks to the players
    default: false
  blockentitiesplus.break:
    description: Allows to break blocks to the players
    default: false